# Generated by Django 2.1 on 2019-11-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191118_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'permissions': [('can_add_product_to_order', 'Может добавлять товары в заказ'), ('can_update_product_in_order', 'Может редактировать товары в заказе'), ('can_delete_product_from_order', 'Может удалять товары из заказа')], 'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказах'},
        ),
    ]
